"""Deterministic export support services."""

from __future__ import annotations

import json
from dataclasses import dataclass
from hashlib import sha256
from pathlib import Path
from typing import Any
from zipfile import ZIP_DEFLATED, ZipFile

from reports.benchmark import BenchmarkReport
from reports.bias import BiasReport
from reports.dataset_intelligence import DatasetIntelligenceReport
from reports.quality import QualityReport
from reports.recommendation import RecommendationReport


class ChecksumService:
    """Compute SHA-256 checksums for generated artifacts."""

    def checksums(self, paths: list[Path]) -> dict[str, str]:
        """Return checksums keyed by artifact filename."""
        return {path.name: self.sha256(path) for path in paths}

    def sha256(self, path: Path) -> str:
        """Return the SHA-256 checksum for one path."""
        digest = sha256()
        with path.open("rb") as handle:
            for chunk in iter(lambda: handle.read(1024 * 1024), b""):
                digest.update(chunk)
        return digest.hexdigest()


class DatasetCardService:
    """Generate dataset cards for packaged exports."""

    def render(self, state: dict[str, Any]) -> str:
        """Return dataset card Markdown."""
        requirement = state.get("structured_requirement", {})
        dataset = state.get("curated_dataset", {})
        quality = state.get("quality_report", {})
        benchmark = state.get("benchmark_report", {})
        ingestion = state.get("ingestion_summary", {})
        stats = ingestion.get("stats", {})
        return (
            "# Dataset Card\n\n"
            f"Name: {dataset.get('name', 'dataforge-dataset')}\n"
            f"Domain: {requirement.get('domain', 'general')}\n"
            f"Languages: {', '.join(requirement.get('languages', []))}\n"
            f"License: {dataset.get('license', 'unknown')}\n"
            f"Rows: {ingestion.get('row_count', len(dataset.get('rows', [])))}\n"
            f"Columns: {ingestion.get('column_count', 'Unavailable')}\n"
            f"Missing values: {stats.get('missing_cells', 'Unavailable')}\n"
            f"Duplicate rows: {stats.get('duplicate_rows', 'Unavailable')}\n"
            f"Quality score: {quality.get('score', 0)}/100\n"
            f"Benchmark readiness: {benchmark.get('training_readiness', 'Unavailable')}\n"
            f"Source checksum: {stats.get('source_sha256', 'Unavailable')}\n"
            f"Sources: {', '.join(dataset.get('source_lineage', [])) or 'Unavailable'}\n"
            "Generated by: DataForge AI\n"
        )

    def write(self, directory: Path, state: dict[str, Any]) -> Path:
        """Write dataset card and return its path."""
        directory.mkdir(parents=True, exist_ok=True)
        path = directory / "dataset_card.md"
        path.write_text(self.render(state), encoding="utf-8")
        return path

    def write_json(self, directory: Path, state: dict[str, Any]) -> Path:
        """Write dataset card JSON and return its path."""
        requirement = state.get("structured_requirement", {})
        dataset = state.get("curated_dataset", {})
        quality = state.get("quality_report", {})
        benchmark = state.get("benchmark_report", {})
        ingestion = state.get("ingestion_summary", {})
        stats = ingestion.get("stats", {})
        payload = {
            "name": dataset.get("name", "dataforge-dataset"),
            "domain": requirement.get("domain", "general"),
            "languages": requirement.get("languages", []),
            "license": dataset.get("license", "unknown"),
            "rows": ingestion.get("row_count", len(dataset.get("rows", []))),
            "columns": ingestion.get("column_count"),
            "missing_values": stats.get("missing_cells"),
            "duplicate_rows": stats.get("duplicate_rows"),
            "source_checksum": stats.get("source_sha256"),
            "schema": ingestion.get("schema", {}),
            "quality_score": quality.get("score", 0),
            "benchmark_readiness": benchmark.get("training_readiness", "Unavailable"),
            "sources": dataset.get("source_lineage", []),
        }
        directory.mkdir(parents=True, exist_ok=True)
        path = directory / "dataset_card.json"
        path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
        return path


class ReportService:
    """Generate deterministic Markdown reports from execution state."""

    def write_all(self, directory: Path, state: dict[str, Any]) -> list[Path]:
        """Write all package reports and return their paths."""
        directory.mkdir(parents=True, exist_ok=True)
        return [
            QualityReport().write(directory, state),
            BiasReport().write(directory, state),
            BenchmarkReport().write(directory, state),
            RecommendationReport().write(directory, state),
            DatasetIntelligenceReport().write(directory, state),
        ]


class ManifestService:
    """Generate manifest.json for packaged artifacts."""

    def write(
        self,
        directory: Path,
        *,
        task_id: str,
        workflow: str,
        artifacts: list[Path],
        checksums: dict[str, str],
    ) -> Path:
        """Write package manifest and return its path."""
        payload = {
            "project": "DataForge AI",
            "run_id": task_id,
            "workflow": workflow,
            "artifacts": [path.name for path in artifacts],
            "checksums": checksums,
        }
        directory.mkdir(parents=True, exist_ok=True)
        path = directory / "manifest.json"
        path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
        return path


@dataclass(frozen=True)
class ZipResult:
    """ZIP packaging result."""

    zip_path: Path
    manifest_path: Path
    checksums: dict[str, str]


class ZipService:
    """Create final reproducible dataset ZIP archives."""

    def package(
        self,
        zip_path: Path,
        artifacts: dict[str, Path],
    ) -> Path:
        """Package artifacts under their requested archive paths."""
        with ZipFile(zip_path, "w", ZIP_DEFLATED) as archive:
            for archive_path, source_path in artifacts.items():
                archive.write(source_path, archive_path)
        return zip_path


class PackagingService:
    """Coordinate report, card, checksum, manifest, and ZIP services."""

    def __init__(
        self,
        report_service: ReportService | None = None,
        dataset_card_service: DatasetCardService | None = None,
        checksum_service: ChecksumService | None = None,
        manifest_service: ManifestService | None = None,
        zip_service: ZipService | None = None,
    ) -> None:
        self.report_service = report_service or ReportService()
        self.dataset_card_service = dataset_card_service or DatasetCardService()
        self.checksum_service = checksum_service or ChecksumService()
        self.manifest_service = manifest_service or ManifestService()
        self.zip_service = zip_service or ZipService()

    def package(
        self,
        artifacts_dir: Path,
        state: dict[str, Any],
        *,
        task_id: str,
        workflow: str,
    ) -> ZipResult:
        """Generate all deterministic export artifacts and package them."""
        reports_dir = artifacts_dir / "reports"
        report_paths = [Path(path) for path in state.get("reports", [])]
        if not report_paths:
            report_paths = self.report_service.write_all(reports_dir, state)
        dataset_card_md = self.dataset_card_service.write(artifacts_dir, state)
        dataset_card_json = self.dataset_card_service.write_json(artifacts_dir, state)
        dataset_path = Path(state["formatted_dataset"])
        artifact_paths = [dataset_path, dataset_card_md, dataset_card_json, *report_paths]
        checksums = self.checksum_service.checksums(artifact_paths)
        manifest_path = self.manifest_service.write(
            artifacts_dir,
            task_id=task_id,
            workflow=workflow,
            artifacts=artifact_paths,
            checksums=checksums,
        )
        zip_path = artifacts_dir / "dataset.zip"
        archive_artifacts = {
            "dataset.jsonl": dataset_path,
            "dataset_card.md": dataset_card_md,
            "dataset_card.json": dataset_card_json,
            "manifest.json": manifest_path,
        }
        archive_artifacts.update(
            {f"reports/{path.name}": path for path in report_paths}
        )
        self.zip_service.package(zip_path, archive_artifacts)
        return ZipResult(
            zip_path=zip_path,
            manifest_path=manifest_path,
            checksums=checksums,
        )
