"""Machine-readable planner and agent capability cards."""

from __future__ import annotations

from typing import Any

from backend.core.registry import AGENT_REGISTRY


PLANNER_CARD: dict[str, Any] = {
    "id": "planner",
    "name": "Planner",
    "version": "1.0",
    "category": "orchestration",
    "registry_agent": False,
    "optional": False,
    "parallelizable": False,
    "mission": "Build a custom execution graph by selecting and ordering agents from the Agent Registry, then estimate cost, time, and quality.",
    "inputs": ["Requirement", "AgentRegistry"],
    "outputs": ["ExecutionGraph", "CostEstimate", "TimeEstimate", "QualityEstimate"],
    "tools": {
        "required": ["Workflow Library", "Graph Validator", "Agent Registry"],
        "optional": ["NVIDIA NIM", "Nemotron"],
    },
    "constraints": [
        "Never modify datasets.",
        "Prefer search and curation over generation.",
        "Use Workflow Library entries and legal mutations.",
        "Validate every graph before execution.",
    ],
    "success": ["Graph contains only necessary agents.", "Estimates remain explainable."],
    "failure": {
        "retryable": False,
        "max_retries": 0,
        "fallback": [],
        "returns": ["planning_error"],
    },
    "quality_targets": {"minimum_confidence": 0.8},
    "reads": ["requirement", "agent_registry", "workflow_library"],
    "writes": ["execution_graph", "planner_rationale", "planner_mutations"],
    "events": ["on_start", "on_complete", "on_failure"],
}


CARD_DETAILS: dict[str, dict[str, Any]] = {
    "requirement_analyzer": {
        "mission": "Convert the user's natural language request into a structured Requirement object.",
        "inputs": ["user_prompt"],
        "outputs": ["Requirement"],
        "tools": {"required": [], "optional": ["NVIDIA NIM", "Nemotron"]},
        "constraints": ["Do not ask questions.", "Leave missing fields as UNSPECIFIED."],
        "success": ["All extractable fields are populated."],
        "failure": {"retryable": True, "max_retries": 1, "fallback": ["clarification"], "returns": ["partial_requirement"]},
        "quality_targets": {"minimum_confidence": 0.85},
        "reads": ["user_prompt"],
        "writes": ["structured_requirement"],
        "events": ["on_start", "on_complete", "on_failure"],
        "capability_tags": ["requirement_parsing", "intent_extraction"],
        "parallelizable": False,
    },
    "clarification": {
        "mission": "Ask the minimum necessary questions to complete the Requirement.",
        "inputs": ["partial_Requirement"],
        "outputs": ["complete_Requirement", "clarification_history"],
        "tools": {"required": [], "optional": ["NVIDIA NIM", "Nemotron"]},
        "constraints": ["Ask no more than 5 questions.", "Only ask when the answer changes the downstream plan."],
        "success": ["Mandatory requirement fields are filled or explicitly marked ambiguous."],
        "failure": {"retryable": True, "max_retries": 1, "fallback": ["best_effort_requirement"], "returns": ["ambiguous_requirement"]},
        "quality_targets": {"minimum_confidence": 0.8},
        "reads": ["structured_requirement"],
        "writes": ["clarification_questions", "clarification_history"],
        "events": ["on_start", "on_progress", "on_complete", "on_failure"],
        "capability_tags": ["clarification", "requirement_completion"],
        "parallelizable": False,
    },
    "discovery": {
        "mission": "Search trusted repositories and web metadata sources for candidate datasets.",
        "inputs": ["Requirement"],
        "outputs": ["DatasetCandidate[]"],
        "tools": {"required": ["DiscoveryService"], "optional": ["Hugging Face API", "GitHub API", "Kaggle API", "Web Search API"]},
        "constraints": ["Never download data.", "Pass every candidate to License Agent before ingestion."],
        "success": ["Ranked candidate list is returned when relevant datasets exist."],
        "failure": {"retryable": True, "max_retries": 2, "fallback": ["local_catalog"], "returns": ["empty_candidates", "provider_errors"]},
        "quality_targets": {"minimum_confidence": 0.75},
        "reads": ["structured_requirement"],
        "writes": ["candidate_datasets"],
        "events": ["on_start", "on_progress", "on_complete", "on_failure"],
        "capability_tags": ["dataset_discovery", "metadata_extraction", "candidate_ranking"],
        "parallelizable": True,
    },
    "license": {
        "mission": "Validate legal usability of discovered datasets.",
        "inputs": ["DatasetCandidate[]", "Requirement.intended_use"],
        "outputs": ["approved[]", "rejected[]"],
        "tools": {"required": ["LicensePolicy"], "optional": ["license classifier"]},
        "constraints": ["Unknown license is blocked from automatic ingestion.", "Commercial use rejects incompatible copyleft/non-commercial licenses."],
        "success": ["Every candidate has a license decision and human-readable reason."],
        "failure": {"retryable": False, "max_retries": 0, "fallback": ["manual_review"], "returns": ["unknown_license_rejections"]},
        "quality_targets": {"minimum_confidence": 0.95},
        "reads": ["candidate_datasets", "structured_requirement"],
        "writes": ["compatible_datasets", "license_decisions"],
        "events": ["on_start", "on_complete", "on_failure"],
        "capability_tags": ["license_validation", "legal_gate"],
        "parallelizable": True,
    },
    "merge": {
        "mission": "Combine multiple approved datasets while preserving provenance.",
        "inputs": ["Dataset[]", "merge_strategy"],
        "outputs": ["MergedDataset", "OverlapReport"],
        "tools": {"required": ["schema alignment"], "optional": ["Pandas"]},
        "constraints": ["Preserve source provenance.", "Resolve to a common schema."],
        "success": ["Merged dataset has uniform schema and no known overlap."],
        "failure": {"retryable": True, "max_retries": 1, "fallback": ["single_best_dataset"], "returns": ["conflict_report"]},
        "quality_targets": {"maximum_duplicate_rate": 0.01},
        "reads": ["compatible_datasets"],
        "writes": ["merged_dataset", "overlap_report"],
        "events": ["on_start", "on_complete", "on_failure"],
        "capability_tags": ["dataset_merge", "schema_alignment"],
        "parallelizable": False,
    },
    "cleaning": {
        "mission": "Fix broken records, missing values, and encoding issues.",
        "inputs": ["Dataset"],
        "outputs": ["CleanDataset", "CleaningReport"],
        "tools": {"required": ["Python text processing"], "optional": ["Pandas"]},
        "constraints": ["Do not alter semantic content unless it is a clear encoding fix.", "Flag imputation."],
        "success": ["No malformed records remain."],
        "failure": {"retryable": True, "max_retries": 1, "fallback": ["remove_irrecoverable_records"], "returns": ["partial_clean_dataset"]},
        "quality_targets": {"minimum_confidence": 0.85},
        "reads": ["merged_dataset"],
        "writes": ["clean_dataset", "cleaning_report"],
        "events": ["on_start", "on_progress", "on_complete", "on_failure"],
        "capability_tags": ["data_cleaning", "normalization"],
        "parallelizable": True,
    },
    "curator": {
        "mission": "Deduplicate, remove PII, filter, and normalize datasets.",
        "inputs": ["Dataset", "curation_config"],
        "outputs": ["CuratedDataset", "QualityDelta", "ModificationLog"],
        "tools": {"required": ["DatasetAssemblyService"], "optional": ["NeMo Curator", "Pandas"]},
        "constraints": ["Never remove semantically meaningful samples without logging.", "Log every modification."],
        "success": ["Duplicate ratio is below target and detected PII is removed."],
        "failure": {"retryable": True, "max_retries": 1, "fallback": ["basic_cleaning"], "returns": ["partially_curated_dataset"]},
        "quality_targets": {"maximum_duplicate_rate": 0.01},
        "reads": ["clean_dataset"],
        "writes": ["curated_dataset", "curation_stats"],
        "events": ["on_start", "on_progress", "on_complete", "on_failure"],
        "capability_tags": ["curation", "deduplication", "pii_removal"],
        "parallelizable": True,
    },
    "translation": {
        "mission": "Translate retained dataset content to required languages.",
        "inputs": ["Dataset", "target_languages", "code_switching_spec"],
        "outputs": ["TranslatedDataset", "translation_confidence"],
        "tools": {"required": [], "optional": ["NVIDIA NIM", "Nemotron", "user model"]},
        "constraints": ["Keep original as reference.", "Preserve domain terminology."],
        "success": ["Translation confidence meets target with minimal semantic loss."],
        "failure": {"retryable": True, "max_retries": 2, "fallback": ["untranslated_dataset"], "returns": ["translation_warning"]},
        "quality_targets": {"minimum_confidence": 0.9},
        "reads": ["curated_dataset"],
        "writes": ["translated_dataset"],
        "events": ["on_start", "on_progress", "on_complete", "on_failure"],
        "capability_tags": ["multilingual_translation", "code_switching"],
        "parallelizable": True,
    },
    "quality_evaluator": {
        "mission": "Score datasets on the frozen quality framework without modifying data.",
        "inputs": ["Dataset"],
        "outputs": ["QualityScore", "dimension_scores"],
        "tools": {"required": ["QualityService"], "optional": ["LLM-as-judge"]},
        "constraints": ["Use the defined Quality Scoring Framework.", "Do not modify data."],
        "success": ["Score reflects dataset usability."],
        "failure": {"retryable": True, "max_retries": 1, "fallback": ["estimated_quality_score"], "returns": ["quality_warning"]},
        "quality_targets": {"minimum_quality_score": 85},
        "reads": ["curated_dataset", "structured_requirement"],
        "writes": ["quality_report"],
        "events": ["on_start", "on_complete", "on_failure"],
        "capability_tags": ["quality_scoring", "metric_evaluation"],
        "parallelizable": True,
    },
    "generator": {
        "mission": "Generate synthetic data only to fill gaps identified by the Planner.",
        "inputs": ["MissingDataProfile", "Requirement"],
        "outputs": ["SyntheticDataset", "GenerationMetadata"],
        "tools": {"required": [], "optional": ["NVIDIA NIM", "Nemotron", "prompt templates"]},
        "constraints": ["Generate only the missing portion.", "Tag all synthetic output."],
        "success": ["Samples pass Critic and Validator at the requested quality profile."],
        "failure": {"retryable": True, "max_retries": 2, "fallback": ["partial_synthetic_dataset"], "returns": ["generation_warning"]},
        "quality_targets": {"minimum_quality_score": 90},
        "reads": ["quality_report", "structured_requirement"],
        "writes": ["curated_dataset", "synthetic_samples_added"],
        "events": ["on_start", "on_progress", "on_complete", "on_failure"],
        "capability_tags": ["synthetic_generation", "gap_filling"],
        "parallelizable": False,
    },
    "critic": {
        "mission": "Review generated or curated samples for hallucinations, inconsistency, and unnaturalness.",
        "inputs": ["Dataset"],
        "outputs": ["CriticismResult[]", "overall_acceptability"],
        "tools": {"required": [], "optional": ["NVIDIA NIM", "grammar checks"]},
        "constraints": ["Never modify data.", "Only provide feedback."],
        "success": ["High-severity issues are detected and reported."],
        "failure": {"retryable": True, "max_retries": 1, "fallback": ["rule_based_checks"], "returns": ["critic_warning"]},
        "quality_targets": {"minimum_confidence": 0.85},
        "reads": ["curated_dataset", "quality_report"],
        "writes": ["critique_report"],
        "events": ["on_start", "on_complete", "on_failure"],
        "capability_tags": ["critique", "hallucination_check", "consistency_review"],
        "parallelizable": True,
    },
    "validator": {
        "mission": "Final validation against the Requirement and readiness gates.",
        "inputs": ["Dataset", "Requirement"],
        "outputs": ["ValidationReport", "quality_score"],
        "tools": {"required": ["schema validator", "statistical checks"], "optional": ["LLM spot-check"]},
        "constraints": ["Verify rather than measure.", "Report failed metrics and improvement loops."],
        "success": ["Quality score and readiness meet the selected profile threshold."],
        "failure": {"retryable": False, "max_retries": 0, "fallback": ["improvement_loop"], "returns": ["validation_report"]},
        "quality_targets": {"minimum_quality_score": 90},
        "reads": ["curated_dataset", "quality_report", "critique_report"],
        "writes": ["validation_report"],
        "events": ["on_start", "on_complete", "on_failure"],
        "capability_tags": ["validation", "readiness_gate"],
        "parallelizable": False,
    },
    "bias": {
        "mission": "Evaluate demographic, linguistic, topic, and toxicity bias signals.",
        "inputs": ["Dataset"],
        "outputs": ["BiasReport"],
        "tools": {"required": ["BiasService"], "optional": ["pretrained bias classifiers"]},
        "constraints": ["Best-effort assessment only.", "Do not invent bias findings."],
        "success": ["Representation and toxicity signals are computed or explicitly skipped."],
        "failure": {"retryable": True, "max_retries": 1, "fallback": ["minimal_bias_report"], "returns": ["bias_skip_notice"]},
        "quality_targets": {"minimum_confidence": 0.75},
        "reads": ["curated_dataset"],
        "writes": ["bias_report"],
        "events": ["on_start", "on_complete", "on_failure"],
        "capability_tags": ["bias_detection", "toxicity_check", "distribution_analysis"],
        "parallelizable": True,
    },
    "benchmark": {
        "mission": "Lightweight evaluation of dataset training readiness.",
        "inputs": ["Dataset"],
        "outputs": ["BenchmarkReport"],
        "tools": {"required": ["BenchmarkService"], "optional": ["lm-eval harness", "small model"]},
        "constraints": ["Keep benchmarking minimal.", "Do not perform full training."],
        "success": ["Quantitative readiness metrics are provided."],
        "failure": {"retryable": True, "max_retries": 1, "fallback": ["skipped_benchmark_report"], "returns": ["benchmark_skip_notice"]},
        "quality_targets": {"minimum_confidence": 0.75},
        "reads": ["curated_dataset", "validation_report"],
        "writes": ["benchmark_report"],
        "events": ["on_start", "on_complete", "on_failure"],
        "capability_tags": ["benchmarking", "training_readiness"],
        "parallelizable": True,
    },
    "formatter": {
        "mission": "Convert final dataset or approved candidate metadata to requested output format.",
        "inputs": ["Dataset", "output_format"],
        "outputs": ["formatted_data"],
        "tools": {"required": ["JSONL writer"], "optional": ["Pandas", "PyArrow"]},
        "constraints": ["Preserve metadata.", "Validate schema before export."],
        "success": ["Output file is valid and readable."],
        "failure": {"retryable": False, "max_retries": 0, "fallback": ["supported_formats_error"], "returns": ["format_error"]},
        "quality_targets": {"minimum_confidence": 0.95},
        "reads": ["curated_dataset", "compatible_datasets", "validation_report"],
        "writes": ["formatted_dataset"],
        "events": ["on_start", "on_complete", "on_failure"],
        "capability_tags": ["format_conversion", "schema_export"],
        "parallelizable": False,
    },
    "packaging": {
        "mission": "Bundle the dataset, metadata, dataset card, and reports into a downloadable ZIP.",
        "inputs": ["formatted_data", "reports[]", "metadata"],
        "outputs": ["dataset.zip"],
        "tools": {"required": ["Zip libraries"], "optional": []},
        "constraints": ["Archive must be self-contained and well-structured."],
        "success": ["ZIP includes dataset, dataset card, and reports."],
        "failure": {"retryable": True, "max_retries": 1, "fallback": ["individual_file_downloads"], "returns": ["packaging_error"]},
        "quality_targets": {"minimum_confidence": 0.95},
        "reads": ["formatted_dataset", "quality_report", "bias_report", "benchmark_report"],
        "writes": ["dataset_zip", "dataset_card", "reports"],
        "events": ["on_start", "on_complete", "on_failure"],
        "capability_tags": ["artifact_packaging", "zip_export"],
        "parallelizable": False,
    },
    "explainability": {
        "mission": "Record important decisions and produce a human-readable decision trail.",
        "inputs": ["execution_log", "planner_decisions", "reports"],
        "outputs": ["ExplainabilityReport", "DecisionTrail"],
        "tools": {"required": ["Log formatter", "report template"], "optional": ["NVIDIA NIM"]},
        "constraints": ["Observe only.", "Never alter execution.", "Include rejections, switches, loops, and stops."],
        "success": ["Decision trail is complete and understandable."],
        "failure": {"retryable": True, "max_retries": 1, "fallback": ["partial_explainability_report"], "returns": ["explainability_warning"]},
        "quality_targets": {"minimum_confidence": 0.85},
        "reads": ["planner_rationale", "planner_mutations", "license_decisions", "reports"],
        "writes": ["explainability_report"],
        "events": ["on_start", "on_complete", "on_failure"],
        "capability_tags": ["audit_trail", "explainability", "decision_reporting"],
        "parallelizable": False,
    },
}


def agent_capability_card(agent_id: str) -> dict[str, Any]:
    """Return one machine-readable registry-backed agent capability card."""
    spec = AGENT_REGISTRY[agent_id]
    details = CARD_DETAILS[agent_id]
    summary = spec.summary()
    return {
        "id": agent_id,
        "name": spec.name,
        "version": "1.0",
        "registry_agent": True,
        "category": summary["category"],
        "optional": summary["optional"],
        "parallelizable": details["parallelizable"],
        "mission": details["mission"],
        "inputs": details["inputs"],
        "outputs": details["outputs"],
        "tools": details["tools"],
        "constraints": details["constraints"],
        "success": details["success"],
        "failure": details["failure"],
        "capabilities": details["capability_tags"],
        "dependencies": summary["requires"],
        "requires": summary["requires"],
        "produces": summary["produces"],
        "reads": details["reads"],
        "writes": details["writes"],
        "events": details["events"],
        "quality_targets": details["quality_targets"],
        "llm_required": summary["requires_llm"],
        "gpu_required": False,
        "estimated_cost": summary["estimated_cost"],
        "estimated_runtime_seconds": summary["estimated_runtime_seconds"],
        "preferred_provider": summary["preferred_provider"],
    }


def all_capability_cards(include_planner: bool = True) -> dict[str, dict[str, Any]]:
    """Return planner and registry-backed agent capability cards."""
    cards = {
        agent_id: agent_capability_card(agent_id)
        for agent_id in sorted(AGENT_REGISTRY)
    }
    if include_planner:
        return {"planner": PLANNER_CARD, **cards}
    return cards
