"""Machine-readable manifests for deterministic support services."""

from __future__ import annotations

from typing import Any


SERVICE_MANIFESTS: dict[str, dict[str, Any]] = {
    "report_service": {
        "id": "report_service",
        "name": "ReportService",
        "type": "service",
        "service_type": "runtime",
        "registry_agent": False,
        "version": "1.0",
        "mission": "Generate structured reports describing dataset quality, workflow execution, validation results, and processing history.",
        "inputs": ["ExecutionContext", "DatasetMetadata", "ValidationReport", "BenchmarkReport", "QualityMetrics", "ExplainabilityLog"],
        "outputs": ["dataset_report.md", "dataset_report.json"],
        "tools": {"required": ["Markdown Templates", "JSON Serializer"], "optional": ["Jinja2"]},
        "constraints": [
            "Never modify datasets.",
            "Reports must be deterministic.",
            "Every reported metric must come from execution results.",
            'Missing sections must be marked "Unavailable".',
        ],
        "quality_targets": {"completeness": "100%", "consistency": "100%"},
        "events": ["report_started", "report_completed", "report_failed"],
        "failure": {"retryable": True, "max_retries": 2, "fallback": ["minimal_report"], "returns": ["partial_report"]},
        "estimated_runtime_seconds": 2,
        "estimated_cost": "low",
        "llm_required": False,
        "gpu_required": False,
    },
    "zip_service": {
        "id": "zip_service",
        "name": "ZipService",
        "type": "service",
        "service_type": "runtime",
        "registry_agent": False,
        "version": "1.0",
        "mission": "Package all generated artifacts into a reproducible archive.",
        "inputs": ["formatted_dataset", "reports", "dataset_card", "metadata"],
        "outputs": ["dataset.zip"],
        "tools": {"required": ["zipfile"], "optional": []},
        "constraints": [
            "Preserve directory structure.",
            "Verify checksums.",
            "Include manifest.json.",
            "Never omit required artifacts.",
        ],
        "events": ["archive_started", "archive_completed", "archive_failed"],
        "failure": {"retryable": True, "max_retries": 1, "fallback": ["individual_files"], "returns": ["archive_error"]},
        "estimated_runtime_seconds": 1,
        "estimated_cost": "low",
        "llm_required": False,
        "gpu_required": False,
    },
    "dataset_card_service": {
        "id": "dataset_card_service",
        "name": "DatasetCardService",
        "type": "service",
        "service_type": "runtime",
        "registry_agent": False,
        "version": "1.0",
        "mission": "Produce a standardized dataset card describing the dataset.",
        "inputs": ["ExecutionContext", "DatasetMetadata", "QualityMetrics", "BenchmarkReport"],
        "outputs": ["dataset_card.md", "dataset_card.json"],
        "tools": {"required": ["Markdown Templates", "JSON Serializer"], "optional": []},
        "constraints": [
            "Include source attribution.",
            "Include license.",
            "Include quality score.",
            "Include benchmark summary.",
        ],
        "events": ["dataset_card_started", "dataset_card_completed", "dataset_card_failed"],
        "failure": {"retryable": True, "max_retries": 1, "fallback": ["minimal_dataset_card"], "returns": ["dataset_card_warning"]},
        "estimated_runtime_seconds": 1,
        "estimated_cost": "low",
        "llm_required": False,
        "gpu_required": False,
    },
    "manifest_service": {
        "id": "manifest_service",
        "name": "ManifestService",
        "type": "service",
        "service_type": "runtime",
        "registry_agent": False,
        "version": "1.0",
        "mission": "Generate manifest.json describing project, run, workflow, artifacts, and checksums.",
        "inputs": ["project", "run_id", "workflow", "artifacts", "checksums"],
        "outputs": ["manifest.json"],
        "tools": {"required": ["JSON Serializer"], "optional": []},
        "constraints": ["Manifest must include every packaged artifact.", "Manifest must be deterministic."],
        "events": ["manifest_started", "manifest_completed", "manifest_failed"],
        "failure": {"retryable": True, "max_retries": 1, "fallback": ["minimal_manifest"], "returns": ["manifest_warning"]},
        "estimated_runtime_seconds": 1,
        "estimated_cost": "low",
        "llm_required": False,
        "gpu_required": False,
    },
    "checksum_service": {
        "id": "checksum_service",
        "name": "ChecksumService",
        "type": "service",
        "service_type": "runtime",
        "registry_agent": False,
        "version": "1.0",
        "mission": "Compute SHA-256 checksums for generated artifacts.",
        "inputs": ["artifact_paths"],
        "outputs": ["checksums"],
        "tools": {"required": ["hashlib"], "optional": []},
        "constraints": ["Compute checksums from final artifact bytes."],
        "events": ["checksum_started", "checksum_completed", "checksum_failed"],
        "failure": {"retryable": True, "max_retries": 1, "fallback": ["missing_checksum_notice"], "returns": ["checksum_warning"]},
        "estimated_runtime_seconds": 1,
        "estimated_cost": "low",
        "llm_required": False,
        "gpu_required": False,
    },
    "template_service": {
        "id": "template_service",
        "name": "TemplateService",
        "type": "service",
        "service_type": "runtime",
        "registry_agent": False,
        "version": "1.0",
        "mission": "Render Markdown and future HTML report templates.",
        "inputs": ["template", "context"],
        "outputs": ["rendered_document"],
        "tools": {"required": ["Python formatting"], "optional": ["Jinja2"]},
        "constraints": ["Rendering must be deterministic.", "Missing values must be explicit."],
        "events": ["template_started", "template_completed", "template_failed"],
        "failure": {"retryable": True, "max_retries": 1, "fallback": ["plain_text_render"], "returns": ["template_warning"]},
        "estimated_runtime_seconds": 1,
        "estimated_cost": "low",
        "llm_required": False,
        "gpu_required": False,
    },
    "artifact_storage_service": {
        "id": "artifact_storage_service",
        "name": "ArtifactStorageService",
        "type": "service",
        "service_type": "platform",
        "registry_agent": False,
        "version": "1.0",
        "mission": "Store generated artifacts under the configured artifact root.",
        "inputs": ["artifact_bytes", "artifact_metadata"],
        "outputs": ["artifact_path"],
        "tools": {"required": ["filesystem"], "optional": ["object storage"]},
        "constraints": ["Never store secrets.", "Keep paths inside the artifact root."],
        "events": ["artifact_store_started", "artifact_store_completed", "artifact_store_failed"],
        "failure": {"retryable": True, "max_retries": 1, "fallback": ["local_tmp_storage"], "returns": ["storage_warning"]},
        "estimated_runtime_seconds": 1,
        "estimated_cost": "low",
        "llm_required": False,
        "gpu_required": False,
    },
}


def service_manifest(service_id: str) -> dict[str, Any]:
    """Return one support service manifest."""
    return SERVICE_MANIFESTS[service_id]


def all_service_manifests() -> dict[str, dict[str, Any]]:
    """Return all support service manifests."""
    return SERVICE_MANIFESTS
